### ISSUE TITLE
Exclude based on query parameters

### ISSUE THREAD

**Issue by mkindred** [siteinspector/siteinspector#33]
I'm having trouble limiting useless crawling of various facet links. My site has product category pages with facets containing links, and I'd like to skip crawling every single facet.

So, for example, with a page like `example.com/products/category/type`, there are also hundreds of combinations of the URL with query parameters, e.g. `example.com/products/category/type?field_material_target_id=149`.

It'd be really helpful to exclude based on query parameters, like `/*?field_*`.

I know this is similar to #32, but we don't currently assign 'nofollow' to our facet links.

**Comment by omohokcoj** [comment]
@mkindred a propper `/*?field_*` pattern matching has been implemented in the latest 1.1.0 version

**Comment by mkindred** [comment]
@omohokcoj Is there an updated README.md on the way? The existing installation instructions no longer work for me.

Using the instructions within 'Manually using docker-compose.yml', I get the following. (If you want full output, I can provide.)

```
❯ mkdir siteinspector && cd siteinspector
❯ wget https://raw.githubusercontent.com/siteinspector/siteinspector/master/docker-compose.yml
❯ docker-compose up
[+] Running 3/0
 ⠿ Container siteinspector-postgres-1  Created                                                                                                                                                                0.0s
 ⠿ Container siteinspector-redis-1     Created                                                                                                                                                                0.0s
 ⠿ Container siteinspector-app-1       Created                                                                                                                                                                0.0s
Attaching to siteinspector-app-1, siteinspector-postgres-1, siteinspector-redis-1
siteinspector-redis-1     | 1:C 22 Aug 2022 14:22:42.482 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
siteinspector-redis-1     | 1:C 22 Aug 2022 14:22:42.482 # Redis version=5.0.14, bits=64, commit=00000000, modified=0, pid=1, just started
siteinspector-redis-1     | 1:C 22 Aug 2022 14:22:42.482 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
siteinspector-redis-1     | 1:M 22 Aug 2022 14:22:42.483 * Running mode=standalone, port=6379.
siteinspector-redis-1     | 1:M 22 Aug 2022 14:22:42.483 # Server initialized
siteinspector-redis-1     | 1:M 22 Aug 2022 14:22:42.483 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
siteinspector-redis-1     | 1:M 22 Aug 2022 14:22:42.483 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
siteinspector-redis-1     | 1:M 22 Aug 2022 14:22:42.483 * DB loaded from disk: 0.000 seconds
siteinspector-redis-1     | 1:M 22 Aug 2022 14:22:42.483 * Ready to accept connections
siteinspector-postgres-1  |
siteinspector-postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
siteinspector-postgres-1  |
siteinspector-postgres-1  | 2022-08-22 14:22:42.604 UTC [1] LOG:  starting PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
siteinspector-postgres-1  | 2022-08-22 14:22:42.605 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
siteinspector-postgres-1  | 2022-08-22 14:22:42.605 UTC [1] LOG:  listening on IPv6 address "::", port 5432
siteinspector-postgres-1  | 2022-08-22 14:22:42.618 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
siteinspector-postgres-1  | 2022-08-22 14:22:42.643 UTC [26] LOG:  database system was shut down at 2022-08-22 14:21:36 UTC
siteinspector-postgres-1  | 2022-08-22 14:22:42.650 UTC [1] LOG:  database system is ready to accept connections
siteinspector-app-1       | rake aborted!
siteinspector-app-1       | No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
siteinspector-app-1       |
siteinspector-app-1       | (See full trace by running task with --trace)
siteinspector-app-1 exited with code 1
```

And then:

```
❯ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/siteinspector/siteinspector/master/scripts/docker-install.sh)"
Attaching to projects-app-1, projects-postgres-1, projects-redis-1
projects-postgres-1  | The files belonging to this database system will be owned by user "postgres".
projects-postgres-1  | This user must also own the server process.
projects-postgres-1  |
projects-postgres-1  | The database cluster will be initialized with locale "en_US.utf8".
projects-postgres-1  | The default database encoding has accordingly been set to "UTF8".
projects-postgres-1  | The default text search configuration will be set to "english".
projects-postgres-1  |
projects-postgres-1  | Data page checksums are disabled.
projects-postgres-1  |
projects-postgres-1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
projects-postgres-1  | creating subdirectories ... ok
projects-postgres-1  | selecting dynamic shared memory implementation ... posix
projects-postgres-1  | selecting default max_connections ... 100
projects-postgres-1  | selecting default shared_buffers ... 128MB
projects-postgres-1  | selecting default time zone ... Etc/UTC
projects-postgres-1  | creating configuration files ... ok
projects-redis-1     | 1:C 22 Aug 2022 14:25:58.496 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
projects-redis-1     | 1:C 22 Aug 2022 14:25:58.496 # Redis version=5.0.14, bits=64, commit=00000000, modified=0, pid=1, just started
projects-redis-1     | 1:C 22 Aug 2022 14:25:58.496 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
projects-redis-1     | 1:M 22 Aug 2022 14:25:58.496 * Running mode=standalone, port=6379.
projects-redis-1     | 1:M 22 Aug 2022 14:25:58.496 # Server initialized
projects-redis-1     | 1:M 22 Aug 2022 14:25:58.496 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
projects-redis-1     | 1:M 22 Aug 2022 14:25:58.496 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
projects-redis-1     | 1:M 22 Aug 2022 14:25:58.497 * Ready to accept connections
projects-postgres-1  | running bootstrap script ... ok
projects-postgres-1  | performing post-bootstrap initialization ... ok
projects-app-1       | rake aborted!
projects-app-1       | No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
projects-app-1       |
projects-app-1       | (See full trace by running task with --trace)
projects-postgres-1  | syncing data to disk ... initdb: warning: enabling "trust" authentication for local connections
projects-postgres-1  | You can change this by editing pg_hba.conf or using the option -A, or
projects-postgres-1  | --auth-local and --auth-host, the next time you run initdb.
projects-postgres-1  | ok
projects-postgres-1  |
projects-postgres-1  |
projects-postgres-1  | Success. You can now start the database server using:
projects-postgres-1  |
projects-postgres-1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
projects-postgres-1  |
projects-postgres-1  | waiting for server to start....2022-08-22 14:25:58.956 UTC [47] LOG:  starting PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
projects-postgres-1  | 2022-08-22 14:25:58.959 UTC [47] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
projects-postgres-1  | 2022-08-22 14:25:59.047 UTC [48] LOG:  database system was shut down at 2022-08-22 14:25:58 UTC
projects-postgres-1  | 2022-08-22 14:25:59.053 UTC [47] LOG:  database system is ready to accept connections
projects-postgres-1  |  done
projects-postgres-1  | server started
projects-app-1 exited with code 1
projects-postgres-1  | CREATE DATABASE
projects-postgres-1  |
projects-postgres-1  |
projects-postgres-1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
projects-postgres-1  |
projects-postgres-1  | 2022-08-22 14:25:59.248 UTC [47] LOG:  received fast shutdown request
projects-postgres-1  | waiting for server to shut down....2022-08-22 14:25:59.251 UTC [47] LOG:  aborting any active transactions
projects-postgres-1  | 2022-08-22 14:25:59.252 UTC [47] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
projects-postgres-1  | 2022-08-22 14:25:59.253 UTC [49] LOG:  shutting down
projects-postgres-1  | 2022-08-22 14:25:59.274 UTC [47] LOG:  database system is shut down
projects-postgres-1  |  done
projects-postgres-1  | server stopped
projects-postgres-1  |
projects-postgres-1  | PostgreSQL init process complete; ready for start up.
projects-postgres-1  |
projects-postgres-1  | 2022-08-22 14:25:59.359 UTC [1] LOG:  starting PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
projects-postgres-1  | 2022-08-22 14:25:59.359 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
projects-postgres-1  | 2022-08-22 14:25:59.359 UTC [1] LOG:  listening on IPv6 address "::", port 5432
projects-postgres-1  | 2022-08-22 14:25:59.366 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
projects-postgres-1  | 2022-08-22 14:25:59.383 UTC [65] LOG:  database system was shut down at 2022-08-22 14:25:59 UTC
projects-postgres-1  | 2022-08-22 14:25:59.389 UTC [1] LOG:  database system is ready to accept connections
```

**Comment by mkindred** [comment]
I also tried cloning the repository, and I was able to get to an error page in the browser, but not beyond that.

**Comment by omohokcoj** [comment]
@mkindred my bad - i updated the dockefile to fix the issue and uploaded the new image - try `docker pull siteinspector/siteinspector:latest` - it should fix the issue

**Comment by mkindred** [comment]
I started with a fresh directory again, and:

```
❯ mkdir siteinspector && cd siteinspector
❯ wget https://raw.githubusercontent.com/siteinspector/siteinspector/master/docker-compose.yml
❯ docker-compose up
Attaching to siteinspector-app-1, siteinspector-postgres-1, siteinspector-redis-1
siteinspector-redis-1     | 1:C 24 Aug 2022 22:17:45.306 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
siteinspector-redis-1     | 1:C 24 Aug 2022 22:17:45.306 # Redis version=5.0.14, bits=64, commit=00000000, modified=0, pid=1, just started
siteinspector-redis-1     | 1:C 24 Aug 2022 22:17:45.306 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
siteinspector-redis-1     | 1:M 24 Aug 2022 22:17:45.309 * Running mode=standalone, port=6379.
siteinspector-redis-1     | 1:M 24 Aug 2022 22:17:45.309 # Server initialized
siteinspector-redis-1     | 1:M 24 Aug 2022 22:17:45.309 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
siteinspector-redis-1     | 1:M 24 Aug 2022 22:17:45.309 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
siteinspector-redis-1     | 1:M 24 Aug 2022 22:17:45.309 * Ready to accept connections
siteinspector-postgres-1  | The files belonging to this database system will be owned by user "postgres".
siteinspector-postgres-1  | This user must also own the server process.
siteinspector-postgres-1  |
siteinspector-postgres-1  | The database cluster will be initialized with locale "en_US.utf8".
siteinspector-postgres-1  | The default database encoding has accordingly been set to "UTF8".
siteinspector-postgres-1  | The default text search configuration will be set to "english".
siteinspector-postgres-1  |
siteinspector-postgres-1  | Data page checksums are disabled.
siteinspector-postgres-1  |
siteinspector-postgres-1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
siteinspector-postgres-1  | creating subdirectories ... ok
siteinspector-postgres-1  | selecting dynamic shared memory implementation ... posix
siteinspector-postgres-1  | selecting default max_connections ... 100
siteinspector-postgres-1  | selecting default shared_buffers ... 128MB
siteinspector-postgres-1  | selecting default time zone ... Etc/UTC
siteinspector-postgres-1  | creating configuration files ... ok
siteinspector-postgres-1  | running bootstrap script ... ok
siteinspector-postgres-1  | performing post-bootstrap initialization ... ok
siteinspector-postgres-1  | syncing data to disk ... initdb: warning: enabling "trust" authentication for local connections
siteinspector-postgres-1  | You can change this by editing pg_hba.conf or using the option -A, or
siteinspector-postgres-1  | --auth-local and --auth-host, the next time you run initdb.
siteinspector-postgres-1  | ok
siteinspector-postgres-1  |
siteinspector-postgres-1  |
siteinspector-postgres-1  | Success. You can now start the database server using:
siteinspector-postgres-1  |
siteinspector-postgres-1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
siteinspector-postgres-1  |
siteinspector-postgres-1  | waiting for server to start....2022-08-24 22:17:46.855 UTC [46] LOG:  starting PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
siteinspector-postgres-1  | 2022-08-24 22:17:46.858 UTC [46] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
siteinspector-postgres-1  | 2022-08-24 22:17:46.891 UTC [47] LOG:  database system was shut down at 2022-08-24 22:17:46 UTC
siteinspector-postgres-1  | 2022-08-24 22:17:46.904 UTC [46] LOG:  database system is ready to accept connections
siteinspector-postgres-1  |  done
siteinspector-postgres-1  | server started
siteinspector-postgres-1  | CREATE DATABASE
siteinspector-postgres-1  |
siteinspector-postgres-1  |
siteinspector-postgres-1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
siteinspector-postgres-1  |
siteinspector-postgres-1  | 2022-08-24 22:17:47.168 UTC [46] LOG:  received fast shutdown request
siteinspector-postgres-1  | waiting for server to shut down....2022-08-24 22:17:47.171 UTC [46] LOG:  aborting any active transactions
siteinspector-postgres-1  | 2022-08-24 22:17:47.173 UTC [46] LOG:  background worker "logical replication launcher" (PID 53) exited with exit code 1
siteinspector-postgres-1  | 2022-08-24 22:17:47.174 UTC [48] LOG:  shutting down
siteinspector-postgres-1  | 2022-08-24 22:17:47.216 UTC [46] LOG:  database system is shut down
siteinspector-postgres-1  |  done
siteinspector-postgres-1  | server stopped
siteinspector-postgres-1  |
siteinspector-postgres-1  | PostgreSQL init process complete; ready for start up.
siteinspector-postgres-1  |
siteinspector-postgres-1  | 2022-08-24 22:17:47.290 UTC [1] LOG:  starting PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
siteinspector-postgres-1  | 2022-08-24 22:17:47.290 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
siteinspector-postgres-1  | 2022-08-24 22:17:47.290 UTC [1] LOG:  listening on IPv6 address "::", port 5432
siteinspector-postgres-1  | 2022-08-24 22:17:47.297 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
siteinspector-postgres-1  | 2022-08-24 22:17:47.331 UTC [64] LOG:  database system was shut down at 2022-08-24 22:17:47 UTC
siteinspector-postgres-1  | 2022-08-24 22:17:47.340 UTC [1] LOG:  database system is ready to accept connections
siteinspector-app-1       | rake aborted!
siteinspector-app-1       | ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `bin/rails credentials:edit`
siteinspector-app-1       | /usr/local/bundle/gems/railties-7.0.3.1/lib/rails/application.rb:581:in `validate_secret_key_base'
siteinspector-app-1       | /usr/local/bundle/gems/railties-7.0.3.1/lib/rails/application.rb:419:in `secret_key_base'
siteinspector-app-1       | /usr/local/bundle/gems/devise-4.8.1/lib/devise/secret_key_finder.rb:24:in `key_exists?'
siteinspector-app-1       | /usr/local/bundle/gems/devise-4.8.1/lib/devise/secret_key_finder.rb:16:in `find'
siteinspector-app-1       | /usr/local/bundle/gems/devise-4.8.1/lib/devise/rails.rb:37:in `block in <class:Engine>'
siteinspector-app-1       | /usr/local/bundle/gems/railties-7.0.3.1/lib/rails/initializable.rb:32:in `instance_exec'
siteinspector-app-1       | /usr/local/bundle/gems/railties-7.0.3.1/lib/rails/initializable.rb:32:in `run'
siteinspector-app-1       | /usr/local/bundle/gems/railties-7.0.3.1/lib/rails/initializable.rb:61:in `block in run_initializers'
siteinspector-app-1       | /usr/local/bundle/gems/railties-7.0.3.1/lib/rails/initializable.rb:60:in `run_initializers'
siteinspector-app-1       | /usr/local/bundle/gems/railties-7.0.3.1/lib/rails/application.rb:372:in `initialize!'
siteinspector-app-1       | /opt/siteinspector/config/environment.rb:7:in `<main>'
siteinspector-app-1       | /usr/local/bundle/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
siteinspector-app-1       | /usr/local/bundle/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
siteinspector-app-1       | /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
siteinspector-app-1       | /usr/local/bundle/gems/railties-7.0.3.1/lib/rails/application.rb:348:in `require_environment!'
siteinspector-app-1       | /usr/local/bundle/gems/railties-7.0.3.1/lib/rails/application.rb:511:in `block in run_tasks_blocks'
siteinspector-app-1       | Tasks: TOP => db:migrate => db:load_config => environment
siteinspector-app-1       | (See full trace by running task with --trace)
siteinspector-app-1 exited with code 1
```

**Comment by omohokcoj** [comment]
@mkindred did you specify SECRET_KEY_BASE environment variable?

**Comment by mkindred** [comment]
I was able to get it up and running again. (I don't recall setting the secret_key_base previously, but I understand now.)

Sadly, I'm still having issues implementing the exclude paths. siteinspector is still crawling thousands of URLs like `/products/category/type?field_material_target_id=149`.

I've tried the exclude paths below:
- `/*?field_*`
- `/*/*/*?field_*`
- `/*\?field_*`

For further testing, I excluded `/products*`. From what I'm seeing, it seems that siteinspector will still crawl URLs matching `/products*`, but it won't report any `/products*` links as broken. Is that the intended behavior?

**Comment by mkindred** [comment]
I wasn't able to get the exclude paths to function the way I wanted. (I was hoping that it'd prevent altogether crawling URLs matching that pattern.)

However, I was able to accomplish what I wanted using xpath exclusions.

**Comment by mediaarchitekt** [comment]
@mkindred How did you solve this? I tried to exclude all URLs with "feed" in it using `/feed/*` in the exclude path field, because the results are duplicate to others.

**Comment by mkindred** [comment]
It looks as though the exclude paths will prevent links matching the pattern from showing up in your report, but they don't prevent matching pages from being crawled. So in my case, I couldn't prevent tends of thousands of hits to pages based on search facet links, and bringing the site to its knees.

My solution to prevent those pages from being crawled was:

1. inspect the link(s) to the pages with duplicate content
2. add the xpath pattern selector(s) matching those links to siteinspector

So, for example, I had lots of search facet links I wanted to exclude:

```
<li class="facet-item">
  <input type="checkbox" class="facets-checkbox" id="search-category-casing-beads">
  <label for="search-category-casing-beads"><span class="facet-item__value">Casing Beads</span></label>
  <a href="/search?search_api_fulltext=deflection&amp;product_search%5B0%5D=search_category%3ACasing%20Beads" rel="nofollow" data-drupal-facet-item-id="search-category-casing-beads" data-drupal-facet-item-value="Casing Beads" data-drupal-facet-item-count="39" style="display: none;"><span class="facet-item__value">Casing Beads</span></a>
</li>
```

I created the following xpath selector, containing three elements separated by '|'. The third element is the search facet links:
```
//a[@rel='nofollow']|//div[@id='environment-indicator']/ul/li/a|//li[@class='facet-item']/a
```

In the selector above, I could probably have omitted the 3rd element, since `//a[@rel='nofollow']` covered those facet links. But I didn't originally have the nofollow on my facets.

I hope this helps.

**Comment by mediaarchitekt** [comment]
Thank you very much for your detailed explanaitions. As I can see, xpath is not working for me. Excluding URLs with the exclude path field do not work either for me. Without documentation I'm just guessing. I give it up.

**Comment by omohokcoj** [comment]
@mediaarchitekt you should never give up 😄 
I tested the "exclude path" feature locally and was not able to find any issues with it - basically `/feed/*` is equivalent of `/^\/feed\/.*$/`  regexp.

With an excluded path the amount of pages crawled was lower than without the rule:
<img width="682" alt="image" src="https://user-images.githubusercontent.com/5418788/224504946-02049874-fe83-414d-b474-922c4d219fa9.png">

Maybe you have relative links like './feed/' or absolute like 'https:...../feed/' - in this case you need to add the exact href pattern into the exclude rule to make it work (so that the beginning of the href string matches the pattern)

**Comment by omohokcoj** [comment]
@mediaarchitekt @mkindred i released a new version (1.2.0) with a proper exclude/include glob pattern handling - hope you can give it a try.
